package main

import "fmt"

var Level105 = BuildLevel([]Vial{
	{DBLUE, DGREEN, LBLUE, LBLUE},
	{VIOLET, PINK, LGREEN, GRAY},
	{ORANGE, VIOLET, RED, BROWN},
	{ORANGE, PINK, RED, ORANGE},
	{DGREEN, RED, YELLOW, DBLUE},
	{YELLOW, DGREEN, BROWN, DGREEN},
	{BROWN, VIOLET, RED, BGREEN},
	{BGREEN, VIOLET, PINK, BGREEN},
	{LGREEN, GRAY, LBLUE, DBLUE},
	{BROWN, YELLOW, GRAY, LGREEN},
	{GRAY, YELLOW, BGREEN, DBLUE},
	{LGREEN, LBLUE, PINK, ORANGE},
	{AIR, AIR, AIR, AIR},
	{AIR, AIR, AIR, AIR},
})

var Level106 = BuildLevel([]Vial{
	{VIOLET, RED, BGREEN, PINK},
	{PINK, LGREEN, DBLUE, DBLUE},
	{DBLUE, LBLUE, LBLUE, GRAY},
	{PINK, LGREEN, BGREEN, LGREEN},
	{GRAY, VIOLET, ORANGE, ORANGE},
	{PINK, RED, ORANGE, LGREEN},
	{RED, BGREEN, GRAY, GRAY},
	{ORANGE, VIOLET, RED, BGREEN},
	{VIOLET, DBLUE, LBLUE, LBLUE},
	{AIR, AIR, AIR, AIR},
	{AIR, AIR, AIR, AIR},
})

var Level107 = BuildLevel([]Vial{
	{BGREEN, GRAY, ORANGE, YELLOW},
	{RED, VIOLET, LGREEN, LBLUE},
	{LGREEN, PINK, BGREEN, VIOLET},
	{YELLOW, PINK, RED, BROWN},
	{LGREEN, DBLUE, BROWN, VIOLET},
	{LGREEN, GRAY, VIOLET, YELLOW},
	{ORANGE, GRAY, LBLUE, DGREEN},

	{RED, DGREEN, LBLUE, PINK},
	{DBLUE, DBLUE, LBLUE, BGREEN},
	{DGREEN, BROWN, PINK, ORANGE},
	{GRAY, BGREEN, YELLOW, ORANGE},
	{RED, BROWN, DGREEN, DBLUE},
	{AIR, AIR, AIR, AIR},
	{AIR, AIR, AIR, AIR},
})

func main() {
	InitialiseLevelBuffers(100)
	shortest := true
	fmt.Println("Solving Level 107, find shortest:", shortest)
	sol := Level107.Solve(shortest, true)
	for i, s := range sol {
		fmt.Printf("Move %2d: %2d -> %2d\n", i+1, s[0]+1, s[1]+1)
	}

}
